### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by Nemris** [johnlane/android_apkzip#1]
Good day,

This is Death Mask Salesman from Android SE. I wanted to compliment for your reinterpretation of my **edgar.sh** script. Never would I expect it would've been included into another developer's own handwork.

Since I'm now oriented to other projects, notably my [Mizar](https://github.com/DMSalesman/Mizar) and my Nemris extractor (soon on GitHub), you might consider yourself as the maintainer of Edgar, if you so wish. It is to be intended as licensed under WTFPL.

**Comment by johnlane** [comment]
Thanks, what you did helped me understand some of how Android worked and, as something I found useful, I'm glad I was able to take it forward. Much appreciated.
